### ISSUE TITLE
Protonlaunch ignore program arguments

### ISSUE THREAD

**Issue by h0m3** [h0m3/protonlaunch#1]
I've found that `run` option of proton doesn't support arguments, if you pass any argument it will just ignore and don't launch a thing.

Im still checking a way to add support for arguments on executables, but for now instead of crashing proton I ignore all application parameters and proton will launch the application without parameters.

**Comment by h0m3** [comment]
Added "runinprefix" and bootstrapped prefix in merge 2183ab707fdb8da63e418a3b27e7dd9fe63617ef

**Comment by jampetz** [comment]
Hi, I wonder if you can help me. I'm a little lost with the arguments part.
I want to launch GOG ver. of Cyberpunk, and just not able to do it with arguments. 
For example:
`env _PROTON_VERSION="GE-Proton7-14" protonlaunch cyberpunk2077.exe mangohud %command% --launcher-skip -skipStartScreen`
What am I doing wrong?

**Comment by h0m3** [comment]
> Hi, I wonder if you can help me. I'm a little lost with the arguments part. I want to launch GOG ver. of Cyberpunk, and just not able to do it with arguments. For example: `env _PROTON_VERSION="GE-Proton7-14" protonlaunch cyberpunk2077.exe mangohud %command% --launcher-skip -skipStartScreen` What am I doing wrong?

Hello @jampetz, how are u?

Sure. Lets get by parts. `%command%` is a label that indicate to Steam to replace it by the game command that it will run. Its very useful for steam own games, since you can precede any game with some command or parameter, even if its a steam one. But for non-steam games the `%command%` parameter does nothing, it doesn't get replaced.

Also, as I can see you're trying to run mangohud. Since mangohud is native from Linux you can run it by preceding protonlaunch, if you try to run mangohud from protonlaunch it will try to run it as a Windows executable.

You can do something like: 

`env _PROTON_VERSION="GE-Proton7-14" mangohud protonlaunch cyberpunk2077.exe --launcher-skip -skipStartScreen`

But protonlaunch work similar to wine, since you're not passing any prefix with `PROTONPREFIX` or `WINEPREFIX` it will create and use the default `~/.proton` prefix. 

I don't know if, on wine, you can just call it `cyberpunk2077.exe` or you need to pass the full path of the game inside the prefix (like `C:\\GOG\\cyberpunk2077.exe` or something similar), unfortunately i dont know GOG version of CP2077 so on that front i cannot help you.

If it can help you, searching for ways to run GOG's version of CP2077 on Wine should help you run it on prontonlaunch, since protonlaunch borrows a lot of characteristics from wine.
