### ISSUE TITLE
protonlaunch doesn't work with sudo-ed user

### ISSUE THREAD

**Issue by nicopap** [h0m3/protonlaunch#21]
I installed steam as a separate user. And when running `protonlaunch`, I am usually in a session started with `sudo -iu steam`.

Amazingly, this breaks this script. `protonlaunch` reasonably uses `> /dev/stderr` and `> /dev/stdout` to redirect to corresponding outputs. However, this is not compatible with a sudo session, due to this: https://unix.stackexchange.com/questions/38538/bash-dev-stderr-permission-denied

It's not your fault in fact, this seems to be a bug in the bash shell. I'm unreasonably angry at bash and am abstaining from profanities.

A solution would be to replace all instances of `> /dev/stdout` by  `>&1` and `> /dev/stderr` by `>&2`

**Comment by h0m3** [comment]
Hello,

Sorry the long time to respond. I've added the fix. I dont have `sudo` to test but I've tested with `doas` which have the same redirection issues and it worked. Now it should work with bash.

Its already available on dev branch, thanks! ;)

**Comment by h0m3** [comment]
Hello,

Thanks once again. The changes are merged into main.
